<?php
namespace LSCP\Stripe\Util;

if ( ! defined( 'ABSPATH' ) ) exit;

class ObjectTypes
{
    /**
     * @var array Mapping from object types to resource classes
     */
    const mapping = [
        \LSCP\Stripe\Collection::OBJECT_NAME => \LSCP\Stripe\Collection::class,
        \LSCP\Stripe\Issuing\CardDetails::OBJECT_NAME => \LSCP\Stripe\Issuing\CardDetails::class,
        \LSCP\Stripe\SearchResult::OBJECT_NAME => \LSCP\Stripe\SearchResult::class,
        \LSCP\Stripe\File::OBJECT_NAME_ALT => \LSCP\Stripe\File::class,
        // object classes: The beginning of the section generated from our OpenAPI spec
        \LSCP\Stripe\Account::OBJECT_NAME => \LSCP\Stripe\Account::class,
        \LSCP\Stripe\AccountLink::OBJECT_NAME => \LSCP\Stripe\AccountLink::class,
        \LSCP\Stripe\AccountSession::OBJECT_NAME => \LSCP\Stripe\AccountSession::class,
        \LSCP\Stripe\ApplePayDomain::OBJECT_NAME => \LSCP\Stripe\ApplePayDomain::class,
        \LSCP\Stripe\Application::OBJECT_NAME => \LSCP\Stripe\Application::class,
        \LSCP\Stripe\ApplicationFee::OBJECT_NAME => \LSCP\Stripe\ApplicationFee::class,
        \LSCP\Stripe\ApplicationFeeRefund::OBJECT_NAME => \LSCP\Stripe\ApplicationFeeRefund::class,
        \LSCP\Stripe\Apps\Secret::OBJECT_NAME => \LSCP\Stripe\Apps\Secret::class,
        \LSCP\Stripe\Balance::OBJECT_NAME => \LSCP\Stripe\Balance::class,
        \LSCP\Stripe\BalanceTransaction::OBJECT_NAME => \LSCP\Stripe\BalanceTransaction::class,
        \LSCP\Stripe\BankAccount::OBJECT_NAME => \LSCP\Stripe\BankAccount::class,
        \LSCP\Stripe\Billing\Alert::OBJECT_NAME => \LSCP\Stripe\Billing\Alert::class,
        \LSCP\Stripe\Billing\AlertTriggered::OBJECT_NAME => \LSCP\Stripe\Billing\AlertTriggered::class,
        \LSCP\Stripe\Billing\CreditBalanceSummary::OBJECT_NAME => \LSCP\Stripe\Billing\CreditBalanceSummary::class,
        \LSCP\Stripe\Billing\CreditBalanceTransaction::OBJECT_NAME => \LSCP\Stripe\Billing\CreditBalanceTransaction::class,
        \LSCP\Stripe\Billing\CreditGrant::OBJECT_NAME => \LSCP\Stripe\Billing\CreditGrant::class,
        \LSCP\Stripe\Billing\Meter::OBJECT_NAME => \LSCP\Stripe\Billing\Meter::class,
        \LSCP\Stripe\Billing\MeterEvent::OBJECT_NAME => \LSCP\Stripe\Billing\MeterEvent::class,
        \LSCP\Stripe\Billing\MeterEventAdjustment::OBJECT_NAME => \LSCP\Stripe\Billing\MeterEventAdjustment::class,
        \LSCP\Stripe\Billing\MeterEventSummary::OBJECT_NAME => \LSCP\Stripe\Billing\MeterEventSummary::class,
        \LSCP\Stripe\BillingPortal\Configuration::OBJECT_NAME => \LSCP\Stripe\BillingPortal\Configuration::class,
        \LSCP\Stripe\BillingPortal\Session::OBJECT_NAME => \LSCP\Stripe\BillingPortal\Session::class,
        \LSCP\Stripe\Capability::OBJECT_NAME => \LSCP\Stripe\Capability::class,
        \LSCP\Stripe\Card::OBJECT_NAME => \LSCP\Stripe\Card::class,
        \LSCP\Stripe\CashBalance::OBJECT_NAME => \LSCP\Stripe\CashBalance::class,
        \LSCP\Stripe\Charge::OBJECT_NAME => \LSCP\Stripe\Charge::class,
        \LSCP\Stripe\Checkout\Session::OBJECT_NAME => \LSCP\Stripe\Checkout\Session::class,
        \LSCP\Stripe\Climate\Order::OBJECT_NAME => \LSCP\Stripe\Climate\Order::class,
        \LSCP\Stripe\Climate\Product::OBJECT_NAME => \LSCP\Stripe\Climate\Product::class,
        \LSCP\Stripe\Climate\Supplier::OBJECT_NAME => \LSCP\Stripe\Climate\Supplier::class,
        \LSCP\Stripe\ConfirmationToken::OBJECT_NAME => \LSCP\Stripe\ConfirmationToken::class,
        \LSCP\Stripe\ConnectCollectionTransfer::OBJECT_NAME => \LSCP\Stripe\ConnectCollectionTransfer::class,
        \LSCP\Stripe\CountrySpec::OBJECT_NAME => \LSCP\Stripe\CountrySpec::class,
        \LSCP\Stripe\Coupon::OBJECT_NAME => \LSCP\Stripe\Coupon::class,
        \LSCP\Stripe\CreditNote::OBJECT_NAME => \LSCP\Stripe\CreditNote::class,
        \LSCP\Stripe\CreditNoteLineItem::OBJECT_NAME => \LSCP\Stripe\CreditNoteLineItem::class,
        \LSCP\Stripe\Customer::OBJECT_NAME => \LSCP\Stripe\Customer::class,
        \LSCP\Stripe\CustomerBalanceTransaction::OBJECT_NAME => \LSCP\Stripe\CustomerBalanceTransaction::class,
        \LSCP\Stripe\CustomerCashBalanceTransaction::OBJECT_NAME => \LSCP\Stripe\CustomerCashBalanceTransaction::class,
        \LSCP\Stripe\CustomerSession::OBJECT_NAME => \LSCP\Stripe\CustomerSession::class,
        \LSCP\Stripe\Discount::OBJECT_NAME => \LSCP\Stripe\Discount::class,
        \LSCP\Stripe\Dispute::OBJECT_NAME => \LSCP\Stripe\Dispute::class,
        \LSCP\Stripe\Entitlements\ActiveEntitlement::OBJECT_NAME => \LSCP\Stripe\Entitlements\ActiveEntitlement::class,
        \LSCP\Stripe\Entitlements\ActiveEntitlementSummary::OBJECT_NAME => \LSCP\Stripe\Entitlements\ActiveEntitlementSummary::class,
        \LSCP\Stripe\Entitlements\Feature::OBJECT_NAME => \LSCP\Stripe\Entitlements\Feature::class,
        \LSCP\Stripe\EphemeralKey::OBJECT_NAME => \LSCP\Stripe\EphemeralKey::class,
        \LSCP\Stripe\Event::OBJECT_NAME => \LSCP\Stripe\Event::class,
        \LSCP\Stripe\ExchangeRate::OBJECT_NAME => \LSCP\Stripe\ExchangeRate::class,
        \LSCP\Stripe\File::OBJECT_NAME => \LSCP\Stripe\File::class,
        \LSCP\Stripe\FileLink::OBJECT_NAME => \LSCP\Stripe\FileLink::class,
        \LSCP\Stripe\FinancialConnections\Account::OBJECT_NAME => \LSCP\Stripe\FinancialConnections\Account::class,
        \LSCP\Stripe\FinancialConnections\AccountOwner::OBJECT_NAME => \LSCP\Stripe\FinancialConnections\AccountOwner::class,
        \LSCP\Stripe\FinancialConnections\AccountOwnership::OBJECT_NAME => \LSCP\Stripe\FinancialConnections\AccountOwnership::class,
        \LSCP\Stripe\FinancialConnections\Session::OBJECT_NAME => \LSCP\Stripe\FinancialConnections\Session::class,
        \LSCP\Stripe\FinancialConnections\Transaction::OBJECT_NAME => \LSCP\Stripe\FinancialConnections\Transaction::class,
        \LSCP\Stripe\Forwarding\Request::OBJECT_NAME => \LSCP\Stripe\Forwarding\Request::class,
        \LSCP\Stripe\FundingInstructions::OBJECT_NAME => \LSCP\Stripe\FundingInstructions::class,
        \LSCP\Stripe\Identity\VerificationReport::OBJECT_NAME => \LSCP\Stripe\Identity\VerificationReport::class,
        \LSCP\Stripe\Identity\VerificationSession::OBJECT_NAME => \LSCP\Stripe\Identity\VerificationSession::class,
        \LSCP\Stripe\Invoice::OBJECT_NAME => \LSCP\Stripe\Invoice::class,
        \LSCP\Stripe\InvoiceItem::OBJECT_NAME => \LSCP\Stripe\InvoiceItem::class,
        \LSCP\Stripe\InvoiceLineItem::OBJECT_NAME => \LSCP\Stripe\InvoiceLineItem::class,
        \LSCP\Stripe\InvoiceRenderingTemplate::OBJECT_NAME => \LSCP\Stripe\InvoiceRenderingTemplate::class,
        \LSCP\Stripe\Issuing\Authorization::OBJECT_NAME => \LSCP\Stripe\Issuing\Authorization::class,
        \LSCP\Stripe\Issuing\Card::OBJECT_NAME => \LSCP\Stripe\Issuing\Card::class,
        \LSCP\Stripe\Issuing\Cardholder::OBJECT_NAME => \LSCP\Stripe\Issuing\Cardholder::class,
        \LSCP\Stripe\Issuing\Dispute::OBJECT_NAME => \LSCP\Stripe\Issuing\Dispute::class,
        \LSCP\Stripe\Issuing\PersonalizationDesign::OBJECT_NAME => \LSCP\Stripe\Issuing\PersonalizationDesign::class,
        \LSCP\Stripe\Issuing\PhysicalBundle::OBJECT_NAME => \LSCP\Stripe\Issuing\PhysicalBundle::class,
        \LSCP\Stripe\Issuing\Token::OBJECT_NAME => \LSCP\Stripe\Issuing\Token::class,
        \LSCP\Stripe\Issuing\Transaction::OBJECT_NAME => \LSCP\Stripe\Issuing\Transaction::class,
        \LSCP\Stripe\LineItem::OBJECT_NAME => \LSCP\Stripe\LineItem::class,
        \LSCP\Stripe\LoginLink::OBJECT_NAME => \LSCP\Stripe\LoginLink::class,
        \LSCP\Stripe\Mandate::OBJECT_NAME => \LSCP\Stripe\Mandate::class,
        \LSCP\Stripe\PaymentIntent::OBJECT_NAME => \LSCP\Stripe\PaymentIntent::class,
        \LSCP\Stripe\PaymentLink::OBJECT_NAME => \LSCP\Stripe\PaymentLink::class,
        \LSCP\Stripe\PaymentMethod::OBJECT_NAME => \LSCP\Stripe\PaymentMethod::class,
        \LSCP\Stripe\PaymentMethodConfiguration::OBJECT_NAME => \LSCP\Stripe\PaymentMethodConfiguration::class,
        \LSCP\Stripe\PaymentMethodDomain::OBJECT_NAME => \LSCP\Stripe\PaymentMethodDomain::class,
        \LSCP\Stripe\Payout::OBJECT_NAME => \LSCP\Stripe\Payout::class,
        \LSCP\Stripe\Person::OBJECT_NAME => \LSCP\Stripe\Person::class,
        \LSCP\Stripe\Plan::OBJECT_NAME => \LSCP\Stripe\Plan::class,
        \LSCP\Stripe\Price::OBJECT_NAME => \LSCP\Stripe\Price::class,
        \LSCP\Stripe\Product::OBJECT_NAME => \LSCP\Stripe\Product::class,
        \LSCP\Stripe\ProductFeature::OBJECT_NAME => \LSCP\Stripe\ProductFeature::class,
        \LSCP\Stripe\PromotionCode::OBJECT_NAME => \LSCP\Stripe\PromotionCode::class,
        \LSCP\Stripe\Quote::OBJECT_NAME => \LSCP\Stripe\Quote::class,
        \LSCP\Stripe\Radar\EarlyFraudWarning::OBJECT_NAME => \LSCP\Stripe\Radar\EarlyFraudWarning::class,
        \LSCP\Stripe\Radar\ValueList::OBJECT_NAME => \LSCP\Stripe\Radar\ValueList::class,
        \LSCP\Stripe\Radar\ValueListItem::OBJECT_NAME => \LSCP\Stripe\Radar\ValueListItem::class,
        \LSCP\Stripe\Refund::OBJECT_NAME => \LSCP\Stripe\Refund::class,
        \LSCP\Stripe\Reporting\ReportRun::OBJECT_NAME => \LSCP\Stripe\Reporting\ReportRun::class,
        \LSCP\Stripe\Reporting\ReportType::OBJECT_NAME => \LSCP\Stripe\Reporting\ReportType::class,
        \LSCP\Stripe\ReserveTransaction::OBJECT_NAME => \LSCP\Stripe\ReserveTransaction::class,
        \LSCP\Stripe\Review::OBJECT_NAME => \LSCP\Stripe\Review::class,
        \LSCP\Stripe\SetupAttempt::OBJECT_NAME => \LSCP\Stripe\SetupAttempt::class,
        \LSCP\Stripe\SetupIntent::OBJECT_NAME => \LSCP\Stripe\SetupIntent::class,
        \LSCP\Stripe\ShippingRate::OBJECT_NAME => \LSCP\Stripe\ShippingRate::class,
        \LSCP\Stripe\Sigma\ScheduledQueryRun::OBJECT_NAME => \LSCP\Stripe\Sigma\ScheduledQueryRun::class,
        \LSCP\Stripe\Source::OBJECT_NAME => \LSCP\Stripe\Source::class,
        \LSCP\Stripe\SourceMandateNotification::OBJECT_NAME => \LSCP\Stripe\SourceMandateNotification::class,
        \LSCP\Stripe\SourceTransaction::OBJECT_NAME => \LSCP\Stripe\SourceTransaction::class,
        \LSCP\Stripe\Subscription::OBJECT_NAME => \LSCP\Stripe\Subscription::class,
        \LSCP\Stripe\SubscriptionItem::OBJECT_NAME => \LSCP\Stripe\SubscriptionItem::class,
        \LSCP\Stripe\SubscriptionSchedule::OBJECT_NAME => \LSCP\Stripe\SubscriptionSchedule::class,
        \LSCP\Stripe\Tax\Calculation::OBJECT_NAME => \LSCP\Stripe\Tax\Calculation::class,
        \LSCP\Stripe\Tax\CalculationLineItem::OBJECT_NAME => \LSCP\Stripe\Tax\CalculationLineItem::class,
        \LSCP\Stripe\Tax\Registration::OBJECT_NAME => \LSCP\Stripe\Tax\Registration::class,
        \LSCP\Stripe\Tax\Settings::OBJECT_NAME => \LSCP\Stripe\Tax\Settings::class,
        \LSCP\Stripe\Tax\Transaction::OBJECT_NAME => \LSCP\Stripe\Tax\Transaction::class,
        \LSCP\Stripe\Tax\TransactionLineItem::OBJECT_NAME => \LSCP\Stripe\Tax\TransactionLineItem::class,
        \LSCP\Stripe\TaxCode::OBJECT_NAME => \LSCP\Stripe\TaxCode::class,
        \LSCP\Stripe\TaxDeductedAtSource::OBJECT_NAME => \LSCP\Stripe\TaxDeductedAtSource::class,
        \LSCP\Stripe\TaxId::OBJECT_NAME => \LSCP\Stripe\TaxId::class,
        \LSCP\Stripe\TaxRate::OBJECT_NAME => \LSCP\Stripe\TaxRate::class,
        \LSCP\Stripe\Terminal\Configuration::OBJECT_NAME => \LSCP\Stripe\Terminal\Configuration::class,
        \LSCP\Stripe\Terminal\ConnectionToken::OBJECT_NAME => \LSCP\Stripe\Terminal\ConnectionToken::class,
        \LSCP\Stripe\Terminal\Location::OBJECT_NAME => \LSCP\Stripe\Terminal\Location::class,
        \LSCP\Stripe\Terminal\Reader::OBJECT_NAME => \LSCP\Stripe\Terminal\Reader::class,
        \LSCP\Stripe\TestHelpers\TestClock::OBJECT_NAME => \LSCP\Stripe\TestHelpers\TestClock::class,
        \LSCP\Stripe\Token::OBJECT_NAME => \LSCP\Stripe\Token::class,
        \LSCP\Stripe\Topup::OBJECT_NAME => \LSCP\Stripe\Topup::class,
        \LSCP\Stripe\Transfer::OBJECT_NAME => \LSCP\Stripe\Transfer::class,
        \LSCP\Stripe\TransferReversal::OBJECT_NAME => \LSCP\Stripe\TransferReversal::class,
        \LSCP\Stripe\Treasury\CreditReversal::OBJECT_NAME => \LSCP\Stripe\Treasury\CreditReversal::class,
        \LSCP\Stripe\Treasury\DebitReversal::OBJECT_NAME => \LSCP\Stripe\Treasury\DebitReversal::class,
        \LSCP\Stripe\Treasury\FinancialAccount::OBJECT_NAME => \LSCP\Stripe\Treasury\FinancialAccount::class,
        \LSCP\Stripe\Treasury\FinancialAccountFeatures::OBJECT_NAME => \LSCP\Stripe\Treasury\FinancialAccountFeatures::class,
        \LSCP\Stripe\Treasury\InboundTransfer::OBJECT_NAME => \LSCP\Stripe\Treasury\InboundTransfer::class,
        \LSCP\Stripe\Treasury\OutboundPayment::OBJECT_NAME => \LSCP\Stripe\Treasury\OutboundPayment::class,
        \LSCP\Stripe\Treasury\OutboundTransfer::OBJECT_NAME => \LSCP\Stripe\Treasury\OutboundTransfer::class,
        \LSCP\Stripe\Treasury\ReceivedCredit::OBJECT_NAME => \LSCP\Stripe\Treasury\ReceivedCredit::class,
        \LSCP\Stripe\Treasury\ReceivedDebit::OBJECT_NAME => \LSCP\Stripe\Treasury\ReceivedDebit::class,
        \LSCP\Stripe\Treasury\Transaction::OBJECT_NAME => \LSCP\Stripe\Treasury\Transaction::class,
        \LSCP\Stripe\Treasury\TransactionEntry::OBJECT_NAME => \LSCP\Stripe\Treasury\TransactionEntry::class,
        \LSCP\Stripe\UsageRecord::OBJECT_NAME => \LSCP\Stripe\UsageRecord::class,
        \LSCP\Stripe\UsageRecordSummary::OBJECT_NAME => \LSCP\Stripe\UsageRecordSummary::class,
        \LSCP\Stripe\WebhookEndpoint::OBJECT_NAME => \LSCP\Stripe\WebhookEndpoint::class,
    ];
    /**
     * @var array Mapping from v2 object types to resource classes
     */
    const v2Mapping = [
        // V1 Class needed for fetching the right related object
        // TODO: https://go/j/DEVSDK-2204 Make a more standardized fix in codegen for all languages
        \LSCP\Stripe\Billing\Meter::OBJECT_NAME => \LSCP\Stripe\Billing\Meter::class,
        // v2 object classes: The beginning of the section generated from our OpenAPI spec
        \LSCP\Stripe\V2\Billing\MeterEvent::OBJECT_NAME => \LSCP\Stripe\V2\Billing\MeterEvent::class,
        \LSCP\Stripe\V2\Billing\MeterEventAdjustment::OBJECT_NAME => \LSCP\Stripe\V2\Billing\MeterEventAdjustment::class,
        \LSCP\Stripe\V2\Billing\MeterEventSession::OBJECT_NAME => \LSCP\Stripe\V2\Billing\MeterEventSession::class,
        \LSCP\Stripe\V2\Event::OBJECT_NAME => \LSCP\Stripe\V2\Event::class,
    ];
}